package constants

const (
	PREPARE_SUCCESS = iota + 100
	PREPARE_UNRECOGNIZED_STATEMENT
	PREPARE_SYNTAX_ERROR
)

const (
	STATEMENT_SELECT = iota + 1000
	STATEMENT_INSERT
	STATEMENT_DELETE
	STATEMENT_UPDATE
	STATEMENT_CREATE
	STATEMENT_CREATE_DB
	STATEMENT_CREATE_TABLE
	STATEMENT_USE  // for selecting database
	STATEMENT_DROP // drop database
	STATEMENT_DROP_DB
	STATEMENT_DROP_TABLE
)

const (
	EXIT_SUCCESS = iota
	EXIT_FAILURE
)
const (
	META_COMMAND_SUCCESS = iota + 10
	META_COMMAND_UNRECOGNIZED_COMMAND
)

const (
	INT = iota + 50
	FLOAT
	STRING
)
